environment:
  - DISPLAY=:99

build:
  image: registry.rkusa.st/node-chrome:4
  commands:
    - Xvfb :99 -extension RANDR -screen 0 1024x768x24 &
    - npm install --silent
    - npm test

notify:
  email:
    recipients:
      - m+ipoxy@rkusa.st
